api:
  version: v1
  url: /api/${api.version}

server:
  servlet:
    context-path: ${api.url}

spring:
  application:
    name: blog

  datasource:
    hikari:
      maximum-pool-size: 20  # Số lượng tối đa kết nối
      minimum-idle: 5        # Số lượng kết nối tối thiểu trong pool
    url: jdbc:postgresql://${database.url}:${database.port}/${database.db-name}
    username: ${database.username}
    password: ${database.password}

  data:
    redis:
      host: localhost
      port: 6379
      password: ""  # Password for connecting to the Redis server (default is empty)
      lettuce:
        pool: # Connection pool settings
          max-active: 8 # Maximum number of active connections in the pool (uses -1 for no limit)
          max-idle: 8 # Maximum number of idle connections in the pool
          min-idle: 0 # Minimum number of idle connections in the pool
          max-wait: -1ms # Maximum wait time to get a connection from the pool (uses -1 for no limit)
      connect-timeout: 30000 # Connection timeout (in milliseconds)


database:
  url: localhost
  port: 5432
  db-name: blog
  username: nguyen
  password: nguyen